package com.sfeir.common.gwt.client.i18n;

import com.google.gwt.i18n.client.LocalizableResource;

/**
 * Factory generated by the ViewFactoryGenerator which return the Implementation of the view from the View Interface name
 * 
 */
public interface I18nFactory {
    public LocalizableResource createI18n(String i18nClass);
}
