package com.sfeir.common.gwt.client.place;

import java.util.Map;

import com.google.gwt.place.shared.Place;

/**
 * Tokenizer to automatically generated by a generator
 * 
 * 
 */
public interface Tokenizer<P extends Place> extends com.google.gwt.place.shared.PlaceTokenizer<P> {
    /**
     * Get a map of property from the place to save in the token
     * 
     * @param place
     * @return a map with the name of the property and the string value
     */
    public Map<String, String> getPlaceProperties(P place);

    /**
     * Set the properties to the place
     * 
     * @param place
     * @param properties
     */
    public P createPlaceWithProperties(Map<String, String> properties);
    
    /**
     * Create the place
     * 
     * @param place
     */
    public P createPlace();

    /**
     * Get generic properties
     * 
     * @return
     */
    public Map<String, PlaceProperty> getProperties();

    /**
     * 
     * @return return the class type of the Place
     */
    public Class<P> getPlaceType();
    
    public static enum PropertyType {
	STRING, INTEGER, LONG, FLOAT, DOUBLE, BOOLEAN, DATE, LISTSTRING, ENUM
    }
}
