package com.sfeir.common.gwt.client.mvp;

import com.sfeir.common.gwt.client.history.PlaceHistoryMapper;

/**
 * Generated by the generator AppPlaceHistoryGenerator
 * 
 */
public interface AppPlaceHistoryMapper extends PlaceHistoryMapper {
}
