package com.sfeir.common.gwt.client.mvp;


/**
 * Factory generated by the ServiceFactoryGenerator which instantiate the Async Service class from the Service name
 * 
 */
public interface ServiceFactory {
    public Object createService(String serviceName);
}
