package com.sfeir.common.gwt.client.mvp;

/**
 * Factory generated by the ViewFactoryGenerator which return the Implementation of the view from the View Interface name
 * 
 */
public interface ViewFactory {
    public View createView(String viewClass);
}
